build-job:
  stage: build
  script:
    - mvn compile

test-job:
  stage: test
  script:
    - mvn test

deploy-prod:
  stage: deploy
  script:
    - mvn package
    - export PORT=5000
    - fuser -k 5000/tcp || true
    - nohup sh target/bin/simplewebapp > cicd_logfile.log 2>&1 &
    - echo "deploying"
