build-job:
  stage: build
  script:
    - mvn compile

test-job:
  stage: test
  script:
    - mvn test

deploy-prod:
  stage: deploy
  script:
    - dpl --provider=heroku --app=<login>-simplewebapp --api-key=<heroku_api_key>
    - mvn package
    - export PORT=8080
    - fuser -k 8080/tcp || true
    - nohup sh target/bin/simplewebapp > cicd_logfile.log 2>&1 &
    - echo "deploying"
  artifacts:
    paths:
      - cicd_logfile.log
