build-job:
  stage: build
  script:
    - mvn compile

test-job:
  stage: test
  script:
    - mvn test

deploy-prod:
  stage: deploy
  port: 5000
  script:
    - mvn package
    - export PORT=5000
    - sh target/bin/simplewebapp &
    - echo "deployed successfully"
