build-job:
  stage: build
  script:
    - "mvn compile"

test-job:
  stage: test
  script:
    - "mvn test"

deploy-prod:
  stage: deploy
  script:
    - "mvn package"
    - export PORT=5000
    - nohup sh target/bin/simplewebapp > dev/null 2>&1 &
    - echo "deploying"
