stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE_TAG: registry.heroku.com/group52-simplewebapp/web

build-job:
  stage: build
  script:
    - mvn compile
  image: maven:latest

test-job:
  stage: test
  script:
    - mvn test
  image: maven:latest

deploy-prod:
  stage: deploy
  script:
    - mvn package
    - docker login --username=hh1222@ic.ac.uk --password=ba332c39-30a4-44ca-ac6f-59aa03216991 registry.heroku.com
    - docker build -t my-docker-image $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG
    - heroku container:release web --app group52-simplewebapp
  only:
    - master
  image: my-docker-image

