stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - mvn compile
  image: maven:latest

test-job:
  stage: test
  script:
    - mvn test
  image: maven:latest

deploy-prod:
  stage: deploy
  script:
    - mvn package
    - docker login --username=hh1222@ic.ac.uk --password=ba332c39-30a4-44ca-ac6f-59aa03216991 registry.heroku.com
    - docker build -t registry.heroku.com/group52-simplewebapp/web .
    - docker push registry.heroku.com/group52-simplewebapp/web
    - heroku container:release web --app group52-simplewebapp
  only:
    - master
  artifacts:
    paths:
      - cicd_logfile.log
  image: docker:latest  # Use the Docker image for deploying


# deploy-prod:
#   stage: deploy
#   script:
#     # TODO: Change to a Secret Variable
#     # TODO: Split into two deploy jobs, one for staging (VM) and one for production (Heroku)
#     - mvn package
#     - export PORT=5000
#     - fuser -k 5000/tcp || true
#     - nohup sh target/bin/simplewebapp > cicd_logfile.log 2>&1 &
#     - docker build -t my_image .
#     - docker run -e PORT=8080 -p 5000:8080 my_image
#     - dpl --provider=heroku --app=group52-simplewebapp --api-key=ba332c39-30a4-44ca-ac6f-59aa03216991
#     - echo "deploying"
#   artifacts:
#     paths:
#       - cicd_logfile.log
  
  
